language: go
go:
- 1.4.2
before_install:
- go get github.com/tools/godep
- export PATH=$HOME/gopath/bin:$PATH
install: godep go version
script:
- go test -v ./...
notifications:
  email: false
  hipchat:
    rooms:
      secure: YNkYDS0HrQgz+ontRRGkxmA5vkhVdztrEkJEGJDqhuqRdeOKCmAckQipYsW2ynXcVwiBz9I7nis86CIZVS+6GFOOFdCWizV4YoW7ETt/PpHD3R+QqudxxFDwO/6v+Q5roEH6vfri2BplhEz4FNQz3D6vHyAjzH7gfSX46vr+CkU=
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
